name: "Build"

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          yarn install
          yarn build
          yarn test
